### ISSUE TITLE
Refactor and improvement scopes

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/mern-video-streaming#16]
In this issue, we will list down all of the issues we are having in the current repository which we should refactor or remove to improvement our current project structure and code quality. 
Please keep adding your suggestions in the comments section.

কোডিং এ ভালো করার অন্যতম একটা উপায় হল কোডের ভালোমন্দ বোঝা। যেহেতু কোডিং এর পুরোটাই হল চিন্তার ফসল, ফলে অন্যের কোড দেখলে নিজের জানা অনেক কিছুর সাথেই অমিল খুঁজে পাওয়া যায়। এর দ্বারা অন্যের চিন্তার প্যাটার্ন বুঝে ফেলে নিজের কোডিং এর প্যাটার্ন আরো বেটার করা যায়। অন্যদিকে, কোডিং এর যে বিষয়গুলো বর্জনীয় সেগুলো সম্পর্কেও আরো ভালো ধারণা পাওয়া যায়।

আমার চলমান মার্ন ভিডিও স্ট্রিমিং প্রজেক্টে (https://lnkd.in/g8JXBqwT) আমি ইচ্ছা করেই এতদিন পর্যন্ত প্রচুর পরিমান গার্বেজ কোড লিখেছি। প্ল্যান ছিল আপনাদের সাথে এগুলো আলোচনা করে আর্কিটেকচারটিকে আরো বেটার করবো। সেজন্যই আমি বেটার / রিফ্যাক্টর করার মতো সমস্ত বিষয়গুলো লিস্ট করতেছি যেগুলো আমাদেরকে ফিক্স করতে হবে, এরপর এগুলো নিয়ে ভিডিও বানাবো।

আপনাদের জন্য একটা টেস্ট আছে। সেটা হল, এই রিপোজিটরিতে গিয়ে কোড গুলো ঘাটাঘাটি করে দেখেন কি কি বিষয়ে আপনি ইম্প্রুভ করার মতো খুঁজে পান। সেগুলো এই ইস্যু এর কমেন্টে গিয়ে যোগ করুন। এটা একটা ফান একটিভিটি হিসেবে নিতে পারেন।

**Comment by foyzulkarim** [comment]
Create a constant file to use URL and remove hardcoded URL strings from client's react components.

**Comment by Fahim-Titan** [comment]
Moving away from using hardcoded connection strings/ports to connect databases. We should use .env file to handle that.

**Comment by Fahim-Titan** [comment]
There are a lot of console logs which might be beneficial for development, but in production console logs won't be the best solution. We can integrate a simple logger (could be winston or logger) and configure that to print data in console logs when in dev environment and in prod it can be saved in txt or any other file format.

**Comment by abid1174** [comment]
Save files to a cloud storage instead of local directories. Create CDN of them.

**Comment by foyzulkarim** [comment]
thanks
