### ISSUE TITLE
Task : If a video is clicked, increase the view count in the database and show the view in the UI

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/mern-video-streaming#21]

**Comment by kabir-webDev** [comment]
I want to contribute to this issue, but I couldn't find the CONTRIBUTING.md file for the contribution guidelines. Where can I find it?

**Comment by foyzulkarim** [comment]
Thanks for commenting. I didn't create the guideline yet. Feel free to implement the issue and collaborate with me via this comment thread or discussion, or anywhere you feel comfortable.  thanks 👍
