### ISSUE TITLE
create folders script

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/mern-video-streaming#24]
In server folder, we need to create some subfolders where the videos will be uploaded and processed.

**Comment by foyzulkarim** [comment]
The thing is, this step is manually created on a fresh machine. 
I was thinking to use `zx` to create the folders. 
Jist fancy ways to do stuffs. 😅

Example command: `npm run init-directories` 

I am happy to hear more suggestions.

**Comment by aninda052** [comment]
oh, i remember that i had to create `uploads` folder manually before running the project. Without these folders, system will break. 
We can create(if them are not already created) these folder/sub-folders automatically after running `npm run start`.  This way we never have to think about those folder, neither our system will break from not creating them.

**Comment by foyzulkarim** [comment]
It is not a good idea to mix different things into single place. We don't need to check every time coz it is a part of setup process, similar as mongodb connection url thing. 
You can do it as you see fit, we can discuss or refactor later. 🙂

**Comment by aninda052** [comment]
sorry for the multiple commit messages. :(

**Comment by foyzulkarim** [comment]
You can try using `zx` library. you can do conditional shell scripting using javascript by using this library.

**Comment by foyzulkarim** [comment]
it is done
