### ISSUE TITLE
Package Vulnerabilities related to pm2

### ISSUE THREAD

**Issue by hanifsheikh** [foyzulkarim/mern-video-streaming#39]
The package @pm2/agent depends on vulnerable versions of proxy-agent and semver.
The package @pm2/io depends on a vulnerable version of semver.
The package pm2 depends on vulnerable versions of @pm2/agent and @pm2/io.
The package degenerator depends on vulnerable versions of vm2.
The package pac-resolver depends on vulnerable versions of degenerator.
The package pac-proxy-agent depends on vulnerable versions of pac-resolver.
The package proxy-agent depends on vulnerable versions of pac-proxy-agent.
In total, there are 9 vulnerabilities, with 3 of them being moderate and 6 being critical.

**Comment by foyzulkarim** [comment]
Do you have any plan to send pull request?

**Comment by hanifsheikh** [comment]
Yes, I want to contribute
