### ISSUE TITLE
update video status to `published` when processing is finished

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/mern-video-streaming#46]
when we upload the video, we will set status `pending`
when we finish the full processing, then we set the status to `published`

**Comment by foyzulkarim** [comment]
@aninda052  you can do this task first if you are interested. 🙂

**Comment by aninda052** [comment]
> @aninda052 you can do this task first if you are interested. slightly_smiling_face

on it vai. :)

**Comment by aninda052** [comment]
@foyzulkarim vai, we take `visibility` input from client. if we set `pending` as default value while uploading a video(we can do this from server side) , then i think we should remove `visibility` field from client. Is there any other  need for `visibility` filed? if yes, then we can use another filed called `status` and set `pending` as default value from the server side.
