### ISSUE TITLE
(Server) Implement generic `Delete` mechanism

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/mern-video-streaming#54]
Currently we already have `insert` and some other generic functions.  Follow those to create this generic `deleteById`  function.

**Comment by ysnarafat** [comment]
Assign this to me.

**Comment by ysnarafat** [comment]
> Can you try to assign it yourself brother?

I see no option to assign users(myself) from `Assignees`.

![image](https://github.com/foyzulkarim/mern-video-streaming/assets/52292674/983a1839-85d2-46c4-84e1-d4adfec2d798)
