### ISSUE TITLE
script doesn't create uploads folders on macOS (apple silicon)

### ISSUE THREAD

**Issue by HasanMukit** [foyzulkarim/mern-video-streaming#57]
As described in the Readme.
```bash
npm i -g zx
npm run init-directories
``` 
should create an `uploads` folder. But when the script was run using `zsh` on macOS Ventura 13.4.1 (c), nothing happened. Upload folders needed to be created manually.  This should be mentioned in the Readme

**Comment by foyzulkarim** [comment]
I tested. You are right. would you like to create  a fix?

**Comment by foyzulkarim** [comment]
Or if you want I can fix it. The script has some logic problem. That's all.

**Comment by foyzulkarim** [comment]
thanks @aninda052
