### ISSUE TITLE
Not an issue, just some questions

### ISSUE THREAD

**Issue by monir-zaman** [foyzulkarim/mern-video-streaming#9]
What is the latency, why hls not dash, why not exo or shaka player, what about the content protection mechanism?

**Comment by foyzulkarim** [comment]
What is the latency
> I don't know 

why hls not dash
> hls is more used than dash

why not exo or shaka player
> plain `<video>` tag is enough to render hls, so no need to use other players for our current use cases.

what about the content protection mechanism
> nothing, sorry. Purchasing a DRM license is very complex and costly task, which is not aligned with this project.


Thanks for your questions.
